# -*- coding: utf-8 -*-
DEFAULT_URL = ''
DEFAULT_USERNAME = ''
DEFAULT_SERVER = 'smtp.gmail.com:587'
DEFAULT_MAIL_FROM = ''
DEFAULT_MAIL_TO = []
DEFAULT_SMS_API = ''
DEFAULT_NUMBERS = []
DEFAULT_DELAY = 2
DEFAULT_SOUND_DURATION = 25000

DEFAULT_SEND_MAIL = False
DEFAULT_SEND_SMS = False
DEFAULT_SOUND = False
DEFAULT_NO_STOP = False
